#index:
#    path: /
#    controller: App\Controller\DefaultController::index
hello_index:
    path: /hello/{prenom}/{age}
    controller: App\Controller\HelloController::index_perso
    requirements:
      prenom: '[A-Za-z]+'
      age: '[0-9]+'

hello_error_index:
    path: /hello/{prenom}/
    controller: App\Controller\HelloController::index_perso_error
    requirements:
      prenom: '[A-Za-z]+'
      age: '[0-9]+'

telephone_newBdd:
    path: /telephone/new/{marque}/{type}/{taille}/
    controller: App\Controller\TelephoneController::new_perso

telephone_modifyBdd:
    path: /telephone/modify/{id}/{marque}/{type}/{taille}/
    controller: App\Controller\TelephoneController::modify_perso

telephone_remove:
    path: /telephone/remove/{id}/
    controller: App\Controller\TelephoneController::remove_perso

telephone_index:
    path: /telephone/
    controller: App\Controller\TelephoneController::index

telephone_tri:
    path: /telephone/tri
    controller: App\Controller\TelephoneController::tri

telephone_triParMarque:
    path: /telephone/tri/{marque}
    controller: App\Controller\TelephoneController::triParMarque

telephone_triParMarqueQb:
    path: /telephone/triQb/{marque}
    controller: App\Controller\TelephoneController::triParMarqueQb

telephone_triParMarqueTypeQb:
    path: /telephone/triQb/{marque}/{type}
    controller: App\Controller\TelephoneController::triParMarqueTypeQb

telephone_new:
    path: /telephone/new
    controller: App\Controller\TelephoneController::new
